language: node_js
node_js:
  - 0.8
env:
  global:
    - secure: "UnaoVA5iq7Nh4LJgya/fRivfGUcCgmRnxvs0szl2I9Pmzql2o8RRoI58CxWy\nkTbs7Ql4CZ/93DpTkk7nYYaiaheFME+i1BXXz+fTdRTaq4qStEyIiquqzJ0H\n5RWpdSxnRdJsAIarpq0QuMq95ZW3VbLmeCExcGtyzIy96YGPMMk="
install:
  - git submodule update --init --recursive
  - git clone --recursive https://github.com/csnover/dojo2-teststack.git ../teststack
  - cd ../teststack
  - npm install --production
script: node runner.js config=dojo2-core/test/teststack
